### PR TITLE
fix mid sentence autocomplete

### LINKED ISSUE #210: Fix bug when attempting to tab complete a word in the middle of a message
https://user-images.githubusercontent.com/20373896/230465746-3b56b5aa-607b-48b9-a548-c6496b38f0e3.mp4

### PR DESCRIPTION
**Pull request by Riott**
Resolves mid sentence autocomplete by trimming whitespace from the pre and post string slices in the input event handler, and then depending on any trailing whitespace we determine whether we are mid sentence and slightly reformat the search string. 

might not be the most elegant solution so open to plenty of feedback 😄 

autocomplete

resolves #210

### CODE REVIEW

File: assets/chat/js/autocomplete.js [hunk 1]
```diff
@@ -131,9 +132,13 @@ class ChatAutoComplete {
         this.promoteIfSelected();
         const str = this.input.val().toString();
         const offset = this.input[0].selectionStart + 1;
```
Comment (11k) [inline assets/chat/js/autocomplete.js:134]: I did some troubleshooting myself and suspect the issue lies here.

`pre` should be the contents of the input before the caret, and `post` should be the contents after the caret. For autocompletion at the end of the string, the `+ 1` has no effect. With `substring()`, you just get the entire string when `indexEnd` is greater than the length of the string.

```
console.debug("test string".substring(0, 999));
// test string
```

The `+ 1` has an impact on mid-sentence autocompletion, however. It steals one character from the end of `pre` and adds it to the beginning of `post`, which throws things off. To illustrate with the message in the issue
```
Hello Cake, mid-text dg<caret> auto complete does not work...
```
and when you type the second `g`
```
console.debug(pre);
// `Hello Cake, mid-text dg `
console.debug(char);
// `g`
console.debug(post);
// `auto complete does not work...`
console.debug(pre + char + post);
// `Hello Cake, mid-text dg gauto complete does not work...`
```
Pressing `tab` at this point completes for `g` and resolves to `gachiGASM` rather than `dggL`. It also swallows up the `auto`, but let's set that aside for now (a different bug).

Would you mind testing out yourself to confirm removing the `+ 1` also fixes the issue? If so, I prefer this solution because I think it's simpler and addresses the bug more directly.

**Review by 11k — CHANGES_REQUESTED** [review]

**Comment by 11k** [comment]
Just tested your fix and I'm not getting the behavior demonstrated in your video. Tab completing a word in the middle works, but it also always deletes the word to the right of it.

File: assets/chat/js/autocomplete.js (hunk 1 above)
Comment (Riott) [reply assets/chat/js/autocomplete.js]: Yes the simple solution works, good spot I have sorted. :)

File: assets/chat/js/autocomplete.js [hunk 2]
```diff
@@ -130,7 +130,7 @@ class ChatAutoComplete {
       } else if (char.length > 0) {
         this.promoteIfSelected();
         const str = this.input.val().toString();
-        const offset = this.input[0].selectionStart + 1;
+        const offset = this.input[0].selectionStart;
         const pre = str.substring(0, offset);
         const post = str.substring(offset);
         const criteria = buildSearchCriteria(pre + char + post, offset);
```
Comment (11k) [inline assets/chat/js/autocomplete.js:136]: Removing the `+ 1` fixes the issue, but introduces a new bug where the completion suggestions don't take the final letter of the word into account. It seems `buildSearchCriteria()` expects an offset representing the new caret position with the new character.

```suggestion
        const criteria = buildSearchCriteria(pre + char + post, offset + 1);
```

**Review by 11k — CHANGES_REQUESTED** [review]

**Review by 11k — APPROVED** [review]
